POI_CATEGORIES = [
    "自然风光与公园",
    "历史与文化古迹",
    "现代地标与都市景观",
    "逛吃与商业街区",
    "艺文与科教空间",
    "主题游乐与动物园",
    "演出与休闲夜生活",
    "户外运动与康养度假",
]

TRAVEL_GOALS = [
    "relaxation",
    "exploration",
    "culture_learning",
    "social_bonding",
    "photo_checkin",
    "family_fun",
    "adventure",
    "wellness",
]

INTENSITY_LEVELS = [
    "low",
    "medium_low",
    "medium",
    "medium_high",
    "high",
]

CROWD_PREFERENCE = [
    "quiet",
    "moderate",
    "lively",
    "no_preference",
]

INDOOR_OUTDOOR = [
    "indoor",
    "outdoor",
    "mixed",
    "no_preference",
]

BUDGET_LEVELS = [
    "budget",
    "affordable",
    "medium",
    "high",
    "luxury",
]

COMPANION_TYPES = [
    "solo",
    "friends",
    "couple",
    "family",
    "parent_child",
    "elderly",
    "business",
    "classmates",
    "other",
]

TRANSPORT_MODES = [
    "walking",
    "subway",
    "bus",
    "taxi",
    "ride_hailing",
    "bike",
    "self_driving",
    "train",
    "no_preference",
]

ACCEPTANCE_LEVELS = [
    "avoid",
    "acceptable",
    "preferred",
    "no_preference",
]

SPECIAL_GROUPS = [
    "pregnant",
    "infant",
    "toddler",
    "senior",
    "disabled",
    "pet_owner",
]

HARD_DIETARY_TAGS = [
    "vegetarian_only",
    "halal_food_only",
    "no_pork",
    "no_alcohol",
    "non_spicy",
]

ACCESSIBILITY_TAGS = [
    "wheelchair",
    "elevator_needed",
    "hearing_impaired",
    "vision_impaired",
    "stroller_friendly",
]

CULTURAL_CONSTRAINT_TAGS = [
    "halal_food_only",
    "no_alcohol",
    "no_pork",
    "prayer_space",
    "vegetarian_only",
]

CATEGORY_TAG_QUESTION_BANK = {
    "自然风光与公园": {
        "structure_tags": [
            "山岳",
            "峡谷",
            "瀑布",
            "湖泊",
            "河流",
            "海滩",
            "海岛",
            "森林",
            "湿地",
            "草地",
            "花海",
            "地质奇观",
            "城市公园",
            "植物园",
            "国家公园 / 自然保护地",
        ],
        "experience_tags": [
            "徒步",
            "登山",
            "观景",
            "赏花",
            "观鸟",
            "亲水",
            "野餐",
            "骑行",
            "日出 / 日落",
            "摄影",
        ],
        "followup_question": "你更喜欢哪类自然风光或公园体验？",
    },
    "历史与文化古迹": {
        "structure_tags": [
            "宫殿",
            "古城",
            "古镇",
            "古村",
            "城墙 / 关隘",
            "考古遗址",
            "陵墓",
            "寺庙",
            "道观",
            "教堂",
            "清真寺",
            "纪念地",
            "名人故居",
            "古桥",
            "碑刻 / 纪念碑",
        ],
        "experience_tags": [
            "朝代 / 时期",
            "文化类型",
            "皇家",
            "考古",
            "军事",
            "名人",
            "祈福",
            "讲解导览",
        ],
        "followup_question": "你更喜欢哪类历史或文化古迹体验？",
    },
    "现代地标与都市景观": {
        "structure_tags": [
            "观景台",
            "高塔",
            "摩天楼",
            "现代建筑",
            "城市广场",
            "地标雕塑",
            "现代桥梁",
            "滨水天际线",
            "城市景观步道",
        ],
        "experience_tags": [
            "城市俯瞰",
            "夜景",
            "灯光秀",
            "建筑摄影",
            "城市漫步",
            "地标打卡",
            "日落机位",
        ],
        "followup_question": "你更喜欢哪类城市景观体验？",
    },
    "逛吃与商业街区": {
        "structure_tags": [
            "步行街",
            "夜市",
            "小吃街",
            "商圈",
            "购物中心",
            "特色集市",
            "伴手礼街区",
            "潮流街区",
        ],
        "experience_tags": [
            "扫街",
            "美食打卡",
            "地方小吃",
            "咖啡甜品",
            "伴手礼",
            "潮流购物",
            "夜宵",
            "夜经济",
            "本地烟火",
        ],
        "followup_question": "你更喜欢哪类逛吃或商业街区体验？",
    },
    "艺文与科教空间": {
        "structure_tags": [
            "综合博物馆",
            "历史博物馆",
            "美术馆",
            "艺术馆",
            "科技馆",
            "自然博物馆",
            "儿童博物馆",
            "图书馆",
            "文创园区",
            "工业遗址改造空间",
            "天文馆 / 行星馆",
        ],
        "experience_tags": [
            "常设展",
            "特展",
            "互动体验",
            "研学",
            "亲子科普",
            "建筑空间",
            "美学打卡",
            "安静参观",
        ],
        "followup_question": "你更喜欢哪类艺文或科教空间体验？",
    },
    "主题游乐与动物园": {
        "structure_tags": [
            "综合乐园",
            "IP 乐园",
            "水乐园",
            "动物园",
            "海洋馆",
            "野生动物园",
            "影视城",
            "室内乐园",
        ],
        "experience_tags": [
            "刺激项目",
            "亲子项目",
            "巡游",
            "烟花 / 夜场",
            "动物互动",
            "角色 IP",
            "全天游玩",
        ],
        "followup_question": "你更喜欢哪类主题游乐体验？",
    },
    "演出与休闲夜生活": {
        "structure_tags": [
            "剧院",
            "演艺秀场",
            "实景演出场地",
            "Livehouse",
            "音乐厅",
            "相声 / 脱口秀馆",
            "酒吧街",
            "夜店 / Club",
        ],
        "experience_tags": [
            "戏剧",
            "音乐会",
            "脱口秀",
            "驻场秀",
            "实景秀",
            "电子乐",
            "爵士",
            "微醺社交",
            "夜游",
        ],
        "followup_question": "你更喜欢哪类演出或夜生活体验？",
    },
    "户外运动与康养度假": {
        "structure_tags": [
            "滑雪场",
            "漂流点",
            "冲浪点",
            "潜水 / 浮潜点",
            "露营地",
            "温泉",
            "康养中心",
            "度假村",
            "高尔夫",
            "山地运动园区",
            "乡野度假 / 农牧体验",
        ],
        "experience_tags": [
            "运动挑战",
            "装备租赁",
            "教练课程",
            "泡汤疗愈",
            "慢度假",
            "过夜停留",
            "多日游",
            "初学者友好 / 进阶友好",
        ],
        "followup_question": "你更喜欢哪类户外运动或康养度假体验？",
    },
}

RESTAURANT_TAG_OPTIONS = {
    "primary_type": [
        "restaurant",
        "fast_food",
        "snack",
        "cafe",
        "food_street",
        "bar",
        "hotel_restaurant",
    ],
    "cuisine_tags": [
        "local_shanghai",
        "jiangzhe",
        "chinese",
        "sichuan_hunan",
        "cantonese",
        "hotpot",
        "bbq",
        "japanese",
        "korean",
        "western",
        "vegetarian",
        "halal",
        "dessert",
        "coffee_tea",
        "street_food",
        "seafood",
        "noodle_rice",
    ],
    "meal_time_tags": [
        "breakfast",
        "brunch",
        "lunch",
        "afternoon_tea",
        "dinner",
        "late_night",
        "quick_break",
    ],
    "price_level": [
        "budget",
        "affordable",
        "medium",
        "high",
        "luxury",
    ],
    "dietary_restrictions": [
        "vegetarian_available",
        "halal_available",
        "non_spicy_available",
        "contains_pork",
        "contains_beef",
        "contains_seafood",
        "contains_nuts",
        "contains_dairy",
        "contains_alcohol",
        "allergen_info_uncertain",
    ],
    "location_tags": [
        "near_core_scenic_area",
        "near_shopping_area",
        "near_food_area",
        "near_nightlife_area",
        "near_subway",
        "inside_scenic_area",
        "inside_mall",
        "near_hotel_area",
        "route_convenient",
        "detour_risk",
    ],
}

HOTEL_TAG_OPTIONS = {
    "primary_type": [
        "hotel",
        "business_hotel",
        "budget_hotel",
        "luxury_hotel",
        "boutique_hotel",
        "resort",
        "hostel",
        "guesthouse_bnb",
        "serviced_apartment",
    ],
    "service_level": [
        "basic",
        "limited_service",
        "comfort",
        "full_service",
        "luxury",
    ],
    "location_tags": [
        "near_core_scenic_area",
        "near_business_district",
        "near_shopping_area",
        "near_food_area",
        "near_nightlife_area",
        "quiet_area",
        "family_friendly_area",
        "near_airport",
        "near_railway_station",
        "far_from_core_area",
    ],
    "facility_tags": [
        "breakfast_available",
        "laundry",
        "luggage_storage",
        "workspace",
        "family_room",
        "kitchen",
        "elevator",
        "accessible",
        "parking",
        "gym",
        "pool",
        "pet_friendly",
    ],
    "transport_tags": [
        "near_subway",
        "subway_walkable",
        "bus_walkable",
        "taxi_friendly",
        "easy_to_airport",
        "easy_to_railway_station",
        "walkable_to_poi",
        "poor_public_transport",
    ],
    "price_level": [
        "budget",
        "affordable",
        "medium",
        "high",
        "luxury",
    ],
    "safety_risk_tags": [
        "noise_risk",
        "low_safety_confidence",
        "far_from_transport",
        "old_facilities",
        "accessibility_uncertain",
        "high_price_volatility",
        "checkin_time_constraint",
    ],
}

REQUIRED_FIELDS = [
    "departure_city",
    "destination_city",
    "start_date",
    "end_date",
    "traveler_count",
    "companion_type",
    "budget_level",
    "preferred_poi_categories",
]

OPTIONAL_FIELDS = [
    "travel_goals",
    "preferred_structure_tags",
    "preferred_experience_tags",
    "must_see",
    "must_avoid",
    "special_groups",
    "dietary_restrictions",
    "allergy_notes",
    "accessibility_needs",
    "religious_or_cultural_constraints",
    "intensity_preference",
    "crowd_preference",
    "indoor_outdoor_preference",
    "transport_preference",
    "food_preference",
    "accommodation_preference",
    "user_free_text",
]
