from typing import List, Dict

# =====================================================================
# 模拟数据库 (Mock DB) - 完美匹配大类与6大属性的设计
# =====================================================================

MOCK_DB: List[Dict] = [
    {
        "poi_id": "P01",
        "name": "上海之巅观光厅",
        "city": "上海",
        "area": "浦东",
        "categories": ["现代地标与都市景观"],
        "intensity": "low",
        "indoor_outdoor": "indoor",
        "cost_level": "high",
        "price": 180,
        "best_time": ["afternoon", "evening", "night"],
        "suitable_groups": ["friends", "couple", "solo", "elderly"],
        "risk_tags": ["排队久", "门票贵", "恐高"],
        "opening_hours": {"start": "08:30", "end": "22:00"},
        "is_closed": False,
        "description": "中国第一高楼，俯瞰魔都全景，拍照非常好看。"
    },
    {
        "poi_id": "P02",
        "name": "上海迪士尼乐园",
        "city": "上海",
        "area": "浦东",
        "categories": ["主题游乐与动物园"],
        "intensity": "high",
        "indoor_outdoor": "mixed",
        "cost_level": "high",
        "price": 475,
        "best_time": ["morning", "afternoon", "evening", "night"],
        "suitable_groups": ["parent_child", "friends", "couple"],
        "risk_tags": ["排队久", "体力消耗极大", "门票贵"],
        "opening_hours": {"start": "08:30", "end": "21:30"},
        "is_closed": False,
        "description": "点亮心中奇梦，适合全天游玩的梦幻乐园，花车巡游和烟花是必看项目。"
    },
    {
        "poi_id": "P03",
        "name": "外滩",
        "city": "上海",
        "area": "黄浦",
        "categories": ["现代地标与都市景观", "历史与宗教古迹"],
        "intensity": "low",
        "indoor_outdoor": "outdoor",
        "cost_level": "free",
        "price": 0,
        "best_time": ["evening", "night"],
        "suitable_groups": ["solo", "couple", "friends", "parent_child", "elderly"],
        "risk_tags": ["人流密集", "风大"],
        "opening_hours": {"start": "00:00", "end": "23:59"},
        "is_closed": False,
        "description": "万国建筑博览群，魔都最经典的夜景打卡地。"
    },
    {
        "poi_id": "P04",
        "name": "上海博物馆",
        "city": "上海",
        "area": "黄浦",
        "categories": ["艺文与科教空间"],
        "intensity": "medium_low",
        "indoor_outdoor": "indoor",
        "cost_level": "free",
        "price": 0,
        "best_time": ["morning", "afternoon"],
        "suitable_groups": ["solo", "parent_child", "elderly", "friends"],
        "risk_tags": ["预约难", "费脑力"],
        "opening_hours": {"start": "09:00", "end": "17:00"},
        "is_closed": False,
        "description": "汇集中国古代艺术瑰宝，青铜器和陶瓷馆藏极具代表性。"
    },
    {
        "poi_id": "P05",
        "name": "武康路历史街区",
        "city": "上海",
        "area": "徐汇",
        "categories": ["逛吃与商业街区", "历史与宗教古迹"],
        "intensity": "medium",
        "indoor_outdoor": "outdoor",
        "cost_level": "free",
        "price": 0,
        "best_time": ["afternoon"],
        "suitable_groups": ["couple", "friends", "solo"],
        "risk_tags": ["人多拥挤", "交通不便"],
        "opening_hours": {"start": "00:00", "end": "23:59"},
        "is_closed": False,
        "description": "洋房林立的网红马路，梧桐树下喝咖啡的绝佳去处，武康大楼必拍。"
    },
    {
        "poi_id": "P06",
        "name": "辰山植物园",
        "city": "上海",
        "area": "松江",
        "categories": ["自然风光与公园", "户外运动与康养度假"],
        "intensity": "medium_high",
        "indoor_outdoor": "outdoor",
        "cost_level": "low",
        "price": 60,
        "best_time": ["morning", "afternoon"],
        "suitable_groups": ["parent_child", "couple", "friends"],
        "risk_tags": ["暴晒", "距离远", "体力消耗大"],
        "opening_hours": {"start": "08:00", "end": "17:00"},
        "is_closed": False,
        "description": "华东最大的植物园，矿坑花园和温室极具特色，春季赏花圣地。"
    },
    {
        "poi_id": "P07",
        "name": "豫园",
        "city": "上海",
        "area": "黄浦",
        "categories": ["历史与宗教古迹", "逛吃与商业街区"],
        "intensity": "medium",
        "indoor_outdoor": "mixed",
        "cost_level": "low",
        "price": 40,
        "best_time": ["morning", "afternoon", "evening"],
        "suitable_groups": ["elderly", "parent_child", "friends", "couple"],
        "risk_tags": ["节假日极度拥挤", "商业化严重"],
        "opening_hours": {"start": "09:00", "end": "16:30"},
        "is_closed": False,
        "description": "江南古典园林，紧邻城隍庙，体验老上海市井风情。"
    },
    {
        "poi_id": "P08",
        "name": "上海天文馆",
        "city": "上海",
        "area": "浦东",
        "categories": ["艺文与科教空间"],
        "intensity": "medium",
        "indoor_outdoor": "indoor",
        "cost_level": "low",
        "price": 30,
        "best_time": ["morning", "afternoon"],
        "suitable_groups": ["parent_child", "friends"],
        "risk_tags": ["抢票极难", "距离极远"],
        "opening_hours": {"start": "09:30", "end": "16:00"},
        "is_closed": False,
        "description": "全球规模最大的天文馆，建筑设计充满宇宙奥秘感，互动体验极佳。"
    },
    {
        "poi_id": "P09",
        "name": "M50创意园",
        "city": "上海",
        "area": "普陀",
        "categories": ["艺文与科教空间"],
        "intensity": "low",
        "indoor_outdoor": "mixed",
        "cost_level": "free",
        "price": 0,
        "best_time": ["afternoon"],
        "suitable_groups": ["solo", "friends", "couple"],
        "risk_tags": ["部分画廊不开放"],
        "opening_hours": {"start": "10:00", "end": "18:00"},
        "is_closed": False,
        "description": "老厂房改造的艺术街区，遍布画廊、工作室和涂鸦墙，文艺青年必去。"
    },
    {
        "poi_id": "P10",
        "name": "静安寺",
        "city": "上海",
        "area": "静安",
        "categories": ["历史与宗教古迹"],
        "intensity": "low",
        "indoor_outdoor": "mixed",
        "cost_level": "low",
        "price": 50,
        "best_time": ["morning"],
        "suitable_groups": ["elderly", "solo", "friends"],
        "risk_tags": ["香火旺盛"],
        "opening_hours": {"start": "07:30", "end": "17:00"},
        "is_closed": False,
        "description": "闹市中的千年古刹，金顶辉煌，求财祈福胜地。"
    },
    {
        "poi_id": "P11",
        "name": "东方明珠",
        "city": "上海",
        "area": "浦东",
        "categories": ["现代地标与都市景观"],
        "intensity": "medium_low",
        "indoor_outdoor": "indoor",
        "cost_level": "high",
        "price": 199,
        "best_time": ["afternoon", "evening"],
        "suitable_groups": ["parent_child", "elderly", "friends"],
        "risk_tags": ["排队久", "设施略旧"],
        "opening_hours": {"start": "09:00", "end": "21:00"},
        "is_closed": False,
        "description": "最具标志性的上海老牌地标，悬空玻璃走廊是经典体验。"
    },
    {
        "poi_id": "P12",
        "name": "佘山国家森林公园",
        "city": "上海",
        "area": "松江",
        "categories": ["自然风光与公园", "户外运动与康养度假"],
        "intensity": "high",
        "indoor_outdoor": "outdoor",
        "cost_level": "free",
        "price": 0,
        "best_time": ["morning", "afternoon"],
        "suitable_groups": ["friends", "couple", "parent_child"],
        "risk_tags": ["体力消耗极大", "夏季蚊虫多"],
        "opening_hours": {"start": "08:30", "end": "16:30"},
        "is_closed": False,
        "description": "上海罕见的山林景观，适合徒步爬山，山顶有佘山天文台与天主教堂。"
    },
    {
        "poi_id": "P13",
        "name": "ERA时空之旅杂技秀",
        "city": "上海",
        "area": "静安",
        "categories": ["演出与休闲夜生活"],
        "intensity": "low",
        "indoor_outdoor": "indoor",
        "cost_level": "high",
        "price": 280,
        "best_time": ["evening", "night"],
        "suitable_groups": ["couple", "parent_child", "friends"],
        "risk_tags": ["票价高昂"],
        "opening_hours": {"start": "19:30", "end": "21:00"},
        "is_closed": False,
        "description": "结合传统杂技与现代舞台科技的视听盛宴，非常震撼。"
    },
    {
        "poi_id": "P14",
        "name": "新天地",
        "city": "上海",
        "area": "黄浦",
        "categories": ["逛吃与商业街区", "演出与休闲夜生活"],
        "intensity": "low",
        "indoor_outdoor": "mixed",
        "cost_level": "high",
        "price": 0,
        "best_time": ["afternoon", "evening", "night"],
        "suitable_groups": ["couple", "friends", "solo"],
        "risk_tags": ["高消费"],
        "opening_hours": {"start": "10:00", "end": "23:59"},
        "is_closed": False,
        "description": "石库门建筑与现代商业的完美结合，遍布高级餐厅和酒吧。"
    },
    {
        "poi_id": "P15",
        "name": "上海野生动物园",
        "city": "上海",
        "area": "浦东",
        "categories": ["主题游乐与动物园"],
        "intensity": "medium_high",
        "indoor_outdoor": "outdoor",
        "cost_level": "medium",
        "price": 165,
        "best_time": ["morning", "afternoon"],
        "suitable_groups": ["parent_child", "friends"],
        "risk_tags": ["体力消耗大", "味道大", "暴晒"],
        "opening_hours": {"start": "09:00", "end": "17:00"},
        "is_closed": False,
        "description": "可以坐在猛兽车里近距离观看猛兽，非常适合带小孩子游玩。"
    },
    {
        "poi_id": "P16",
        "name": "滴水湖",
        "city": "上海",
        "area": "浦东",
        "categories": ["自然风光与公园", "户外运动与康养度假"],
        "intensity": "medium_low",
        "indoor_outdoor": "outdoor",
        "cost_level": "free",
        "price": 0,
        "best_time": ["afternoon", "evening"],
        "suitable_groups": ["couple", "parent_child", "friends"],
        "risk_tags": ["风大", "极度偏远"],
        "opening_hours": {"start": "00:00", "end": "23:59"},
        "is_closed": False,
        "description": "圆形的人工湖，适合露营、放风筝和环湖骑行，周边配套完善。"
    },
    {
        "poi_id": "P17",
        "name": "1192弄老上海风情街",
        "city": "上海",
        "area": "浦东",
        "categories": ["逛吃与商业街区"],
        "intensity": "low",
        "indoor_outdoor": "indoor",
        "cost_level": "low",
        "price": 0,
        "best_time": ["afternoon", "evening"],
        "suitable_groups": ["friends", "couple", "elderly"],
        "risk_tags": ["人多杂乱"],
        "opening_hours": {"start": "10:00", "end": "22:00"},
        "is_closed": False,
        "description": "位于商场地下，完美复刻了民国时期老上海的街景，适合穿旗袍拍照。"
    },
    {
        "poi_id": "P18",
        "name": "中共一大纪念馆",
        "city": "上海",
        "area": "黄浦",
        "categories": ["历史与宗教古迹", "艺文与科教空间"],
        "intensity": "low",
        "indoor_outdoor": "indoor",
        "cost_level": "free",
        "price": 0,
        "best_time": ["morning", "afternoon"],
        "suitable_groups": ["elderly", "parent_child", "solo"],
        "risk_tags": ["需提前预约", "安检严格"],
        "opening_hours": {"start": "09:00", "end": "17:00"},
        "is_closed": True, # 模拟大修闭馆
        "description": "具有极其重要历史意义的红色景点，展陈运用了大量多媒体技术。"
    },
    {
        "poi_id": "P19",
        "name": "复兴公园",
        "city": "上海",
        "area": "黄浦",
        "categories": ["自然风光与公园"],
        "intensity": "low",
        "indoor_outdoor": "outdoor",
        "cost_level": "free",
        "price": 0,
        "best_time": ["morning", "afternoon"],
        "suitable_groups": ["elderly", "parent_child", "solo"],
        "risk_tags": ["中老年广场舞较多"],
        "opening_hours": {"start": "05:00", "end": "21:00"},
        "is_closed": False,
        "description": "上海唯一的法国法式园林风格公园，沉淀着浓厚的历史气息。"
    },
    {
        "poi_id": "P20",
        "name": "思南公馆",
        "city": "上海",
        "area": "黄浦",
        "categories": ["逛吃与商业街区"],
        "intensity": "low",
        "indoor_outdoor": "mixed",
        "cost_level": "high",
        "price": 0,
        "best_time": ["afternoon", "evening"],
        "suitable_groups": ["couple", "friends"],
        "risk_tags": ["消费昂贵"],
        "opening_hours": {"start": "10:00", "end": "22:00"},
        "is_closed": False,
        "description": "市中心成片的花园洋房区，充满海派风情，周末常有文化市集。"
    }
]

# 消费水平映射表（用于大小比较筛选）
COST_MAP = {"free": 0, "low": 1, "medium": 2, "high": 3}
